# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QgisSweptPath
                                 A QGIS plugin
 Swept Path simulation with qgis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-12-08
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Lukas Gafner
        email                : lugafner@proton.me
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QCoreApplication, Qt
from qgis.PyQt.QtGui import QIcon, QColor
from qgis.PyQt.QtWidgets import QAction
from qgis.core import QgsPoint, QgsGeometry, Qgis
from qgis.gui import QgsRubberBand, QgsGui

# Initialize Qt resources from file resources.py
from .resources import *

# Import the code for the DockWidget
from .qgis_swept_path_dockwidget import QgisSweptPathDockWidget
import os.path

# Import SweptPath code
from threading import Thread
import time
from .vehicle import Vehicle
from .coord import CartesianCoord

class QgisSweptPath:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """ Constructor """
        # Save reference to the QGIS interface
        self.iface = iface

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # Declare instance attributes
        self.actions = []
        self.menu = 'QgisSweptPath'
        # TODO: We are going to let the user set this up in a future iteration
        self.toolbar = self.iface.addToolBar('QgisSweptPath')
        self.toolbar.setObjectName('QgisSweptPath')

        self.pluginIsActive = False
        self.dockwidget = None

        # SweptPath fields
        self._speed: float = 0.5
        self._steering_angle: float = 0.0
        self.simulation_running: bool = False


    def run(self):
        """Run method that loads and starts the plugin"""

        if not self.pluginIsActive:
            self.pluginIsActive = True

            # dockwidget may not exist if:
            #    first run of plugin
            #    removed on close (see self.onClosePlugin method)
            if self.dockwidget == None:
                # Create the dockwidget (after translation) and keep reference
                self.dockwidget = QgisSweptPathDockWidget()

            # connect to provide cleanup on closing of dockwidget
            self.dockwidget.closingPlugin.connect(self.onClosePlugin)

            # Signals
            self.dockwidget.btnStartSimulation.clicked.connect(self.startSimulation)

            # show the dockwidget
            self.iface.addDockWidget(Qt.RightDockWidgetArea, self.dockwidget)
            self.dockwidget.show()

    def setupControls(self):
        """Adds all actions for the controls"""
        # Actions
        a_steer_left = self.add_action("Steer left", self.steer_left, parent=self.iface.mainWindow())
        self.iface.registerMainWindowAction(a_steer_left, "Ctrl+I")
        QgsGui.shortcutsManager().registerAction(a_steer_left)


    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/qgis_swept_path/icon.png'
        self.add_action(
            text='QgisSweptPath',
            callback=self.run,
            icon_path=icon_path,
            enabled_flag=True,
            add_to_menu=True,
            parent=self.iface.mainWindow())  

        self.setupControls()      


    def onClosePlugin(self):
        """Cleanup necessary items here when plugin dockwidget is closed"""
        # disconnects
        self.dockwidget.closingPlugin.disconnect(self.onClosePlugin)
        self.pluginIsActive = False


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu('QgisSweptPath', action)
            self.iface.removeToolBarIcon(action)
            self.iface.unregisterMainWindowAction(action)
        # remove the toolbar
        del self.toolbar


    def add_action(
        self,
        text,
        callback,
        icon_path=None,
        enabled_flag=True,
        add_to_menu=False,
        add_to_toolbar=False,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def update_status(self):
        if self.simulation_running:
            self.dockwidget.lblStatus.setText("Simulation running")
        # Add else if for more specific status
        else:
            self.dockwidget.lblStatus.setText("Status")

    def update_speed(self):
        self.dockwidget.txtSpeed.setText(str(self._speed))

    def update_steering(self):
        self.dockwidget.txtSteeringAngle.setText(str(self._steering_angle / 3.14159 * 180))

    def speed_up(self):
        self._speed += 0.1
        self.update_speed()

    def speed_down(self):
        self._speed -= 0.1
        self.update_speed()

    def steer_left(self):
        self._steering_angle += 1 / 180 * 3.14159
        self.update_steering()
    
    def steer_right(self):
        self._steering_angle -= 1 / 180 * 3.14159
        self.update_steering()
    
    def startSimulation(self):
        self.update_steering()
        self.update_speed()
        
        self.vehicle = Vehicle()
        self.vehicle.place_vehicle(CartesianCoord(0.0, 0.0), 0.0)

        t = Thread(target=self.simulate, args=())
        t.start()

    def simulate(self):
        self.simulation_running = True
        points = []
        for i in range(50):
            self.vehicle.step(self._steering_angle, self._speed)
            point = QgsPoint(self.vehicle._global_f.x, self.vehicle._global_f.y)
            points.append(point)

            self.update_status()
            time.sleep(0.5)

        self.simulation_running = False

        canvas = self.iface.mapCanvas()
        polyline = QgsRubberBand(canvas, Qgis.GeometryType.Line)
        polyline.setToGeometry(QgsGeometry.fromPolyline(points), None)
        polyline.setColor(QColor(255, 0, 0))
        polyline.setWidth(3)

        self.update_status()
