# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QgisSweptPath
                                 A QGIS plugin
 Swept Path simulation with qgis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-12-08
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Lukas Gafner
        email                : lugafner@proton.me
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QCoreApplication, Qt, QVariant
from qgis.PyQt.QtGui import QIcon, QColor
from qgis.PyQt.QtWidgets import QAction
from qgis.core import QgsPoint, QgsGeometry, Qgis, QgsField, QgsPointXY, QgsFeature, QgsVectorLayer
from qgis.gui import QgsRubberBand, QgsGui

# Initialize Qt resources from file resources.py
from .resources import *

# Import the code for the DockWidget
from .qgis_swept_path_dockwidget import QgisSweptPathDockWidget
import os.path

# Import SweptPath code
from threading import Thread
import time
from .vehicle import Vehicle
from .coord import CartesianCoord, CoordUtils

class QgisSweptPath:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """ Constructor """
        # Save reference to the QGIS interface
        self.iface = iface

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # Declare instance attributes
        self.actions = []
        self.menu = "QgisSweptPath"
        # TODO: We are going to let the user set this up in a future iteration
        self.toolbar = self.iface.addToolBar('QgisSweptPath')
        self.toolbar.setObjectName('QgisSweptPath')

        self.pluginIsActive = False
        self.dockwidget = None

        # SweptPath fields
        self.simulation_running: bool = False  # Simulation is running
        self._simulation_id: str = ""  # Simulation ID for layer features identification
        
        self.vehicle: Vehicle = None  # The vehicle to simulate

        # Visualisation
        self._vehicle_layer: QgsVectorLayer = None  # Layer to draw the vehicle during simulation
        self._vehicle_features: dict[Vehicle, QgsFeature] = {}  # Dict with vehicle and the corresponding feature

    def run(self):
        """Run method that loads and starts the plugin"""

        if not self.pluginIsActive:
            self.pluginIsActive = True

            # dockwidget may not exist if:
            #    first run of plugin
            #    removed on close (see self.onClosePlugin method)
            if self.dockwidget == None:
                # Create the dockwidget (after translation) and keep reference
                self.dockwidget = QgisSweptPathDockWidget()

            # connect to provide cleanup on closing of dockwidget
            self.dockwidget.closingPlugin.connect(self.onClosePlugin)

            # Signals
            self.dockwidget.btnStartSimulation.clicked.connect(self.startSimulation)
            self.dockwidget.btnStopSimulation.clicked.connect(self.stopSimulation)
            self.dockwidget.btnAddLayers.clicked.connect(self._create_layers)

            # Setup Controls
            self.setupControls()

            # show the dockwidget
            self.iface.addDockWidget(Qt.RightDockWidgetArea, self.dockwidget)
            self.dockwidget.show()

    def setupControls(self):
        """Adds all actions for the controls"""
        # Actions
        self.add_action("Steer left", self.steer_left, add_to_menu=True, parent=self.iface.mainWindow(), shortcut="Ctrl+Shift+J")
        self.add_action("Steer right", self.steer_right, add_to_menu=True, parent=self.iface.mainWindow(), shortcut="Ctrl+Shift+L")
        self.add_action("Speed up", self.speed_up, add_to_menu=True, parent=self.iface.mainWindow(), shortcut="Ctrl+Shift+IJ")
        self.add_action("Speed down", self.speed_down, add_to_menu=True, parent=self.iface.mainWindow(), shortcut="Ctrl+Shift+K")

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ":/plugins/qgis_swept_path/icon.png"
        self.add_action(
            text="QgisSweptPath",
            callback=self.run,
            icon_path=icon_path,
            enabled_flag=True,
            add_to_menu=True,
            parent=self.iface.mainWindow())      


    def onClosePlugin(self):
        """Cleanup necessary items here when plugin dockwidget is closed"""
        # disconnects
        self.dockwidget.closingPlugin.disconnect(self.onClosePlugin)
        self.pluginIsActive = False


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu('QgisSweptPath', action)
            self.iface.removeToolBarIcon(action)
            self.iface.unregisterMainWindowAction(action)
            QgsGui.shortcutsManager().unregisterAction(action)
        # remove the toolbar
        del self.toolbar


    def add_action(
        self,
        text,
        callback,
        icon_path=None,
        enabled_flag=True,
        add_to_menu=False,
        add_to_toolbar=False,
        status_tip=None,
        whats_this=None,
        parent=None, 
        shortcut=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :param shortcut: Optional text for keyboard shortcut. Default None
        :type shortcut: str

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)
        
        if shortcut is not None:
            self.iface.registerMainWindowAction(action, shortcut)
            QgsGui.shortcutsManager().registerAction(action)
            
        self.actions.append(action)

        return action

    def update_status(self):
        if self.simulation_running:
            self.dockwidget.lblStatus.setText("Simulation running")
        # Add else if for more specific status
        else:
            self.dockwidget.lblStatus.setText("Status")

    def update_speed(self):
        self.dockwidget.txtSpeed.setText(str(self.vehicle.speed))

    def update_steering(self):
        self.dockwidget.txtSteeringAngle.setText(str(self.vehicle.steering_angle / 3.14159 * 180))

    def speed_up(self):
        self.vehicle.speed_up()
        self.update_speed()

    def speed_down(self):
        self.vehicle.speed_down()
        self.update_speed()

    def steer_left(self):
        self.vehicle.steer_left()
        self.update_steering()
    
    def steer_right(self):
        self.vehicle.steer_right()
        self.update_steering()
    
    def stopSimulation(self):
        self.simulation_running = False

    def startSimulation(self):
        self._simulation_id = self.dockwidget.txtSimulationId.text()

        self._setup_vehicle()
        self.vehicle.place_vehicle(CartesianCoord(0.0, 0.0), 0.0)
        self._create_vehicle_drawing()

        self.update_steering()
        self.update_speed()

        t = Thread(target=self.simulate, args=())

        self.simulation_running = True
        t.start()

    def simulate(self):
        points = []
        while self.simulation_running:
            self.vehicle.step()
            point = QgsPoint(self.vehicle.f.x, self.vehicle.f.y)
            points.append(point)
            self._draw_vehicle()

            self.update_status()
            time.sleep(self.vehicle.iteration_break)

        canvas = self.iface.mapCanvas()
        polyline = QgsRubberBand(canvas, Qgis.GeometryType.Line)
        polyline.setToGeometry(QgsGeometry.fromPolyline(points), None)
        polyline.setColor(QColor(255, 0, 0))
        polyline.setWidth(3)

        self.update_status()

    def _setup_vehicle(self):
        # TODO: Add a vehicle factory. Currently the most simple vehicle is generated
        trailer = Vehicle()
        self.vehicle = Vehicle()
        self.vehicle.trailer = trailer
        
    def _draw_vehicle(self):
        self._vehicle_layer.dataProvider().truncate()
        for v, f in self._vehicle_features.items():
            f["rotation"] = CoordUtils.rad_to_degrees(v.a) * -1
            f.setGeometry(QgsGeometry.fromPointXY(QgsPointXY(v.f.x, v.f.y)))
            self._vehicle_layer.dataProvider().addFeatures([f])

        self._vehicle_layer.triggerRepaint()

    def _create_vehicle_drawing(self):
        self._vehicle_layer.dataProvider().truncate()
        for v in self.vehicle.vehicle_parts:
            feature = QgsFeature(self._vehicle_layer.fields())
            feature["symbol"] = v.symbol
            feature["rotation"] = CoordUtils.rad_to_degrees(v.a) * -1
            feature["size_x"] = v.symbol_size_x
            feature["size_y"] = v.symbol_size_y
            feature["offset_x"] = v.symbol_offset_x
            feature["offset_y"] = v.symbol_offset_y
            feature.setGeometry(QgsGeometry.fromPointXY(QgsPointXY(v.f.x, v.f.y)))
            self._vehicle_features[v] = feature

            self._vehicle_layer.dataProvider().addFeatures([feature])

        self._vehicle_layer.triggerRepaint()

    def _create_layers(self):
        if self._vehicle_layer is None:
            self._vehicle_layer = self.iface.addVectorLayer("Point", "vehicle", "memory")
            crs = self._vehicle_layer.crs()
            crs.createFromId(2056)
            self._vehicle_layer.setCrs(crs)
            
            self._vehicle_layer.dataProvider().addAttributes([QgsField("symbol", QVariant.String)])
            self._vehicle_layer.dataProvider().addAttributes([QgsField("rotation", QVariant.Double)])
            self._vehicle_layer.dataProvider().addAttributes([QgsField("size_x", QVariant.Double)])
            self._vehicle_layer.dataProvider().addAttributes([QgsField("size_y", QVariant.Double)])
            self._vehicle_layer.dataProvider().addAttributes([QgsField("offset_x", QVariant.Double)])
            self._vehicle_layer.dataProvider().addAttributes([QgsField("offset_y", QVariant.Double)])
            self._vehicle_layer.updateFields()
