# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QgisSweptPath
                                 A QGIS plugin
 Swept Path simulation with qgis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-12-08
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Lukas Gafner
        email                : lugafner@proton.me
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from qgis.PyQt.QtCore import Qt, QVariant
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.core import QgsPoint, QgsGeometry, QgsField, QgsPointXY, QgsFeature, QgsVectorLayer, Qgis, QgsSettings, QgsProject, QgsVectorFileWriter
from qgis.gui import QgsGui, QgsVectorLayerSaveAsDialog
from threading import Thread
from uuid import uuid4

import time

# Initialize Qt resources from file resources.py

# Import the code for the DockWidget
from .qgis_swept_path_dockwidget import QgisSweptPathDockWidget
import os.path

# Import SweptPath code

from .vehicle import Vehicle
from .vehicles.mercedes_citaro_g import MercedesCitaroG
from .vehicles.mercedes_citaro_g_trailer import MercedesCitaroGTrailer

from .coord import CartesianCoord, CoordUtils
from .vehicle_placer import VehiclePlacer
from .path_points import PathPoints

class QgisSweptPath:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """ Constructor """
        # Save reference to the QGIS interface
        self.iface = iface
        self.canvas = iface.mapCanvas()

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # Declare instance attributes
        self.actions = []
        self.menu = "QgisSweptPath"
        # TODO: We are going to let the user set this up in a future iteration
        self.toolbar = self.iface.addToolBar('QgisSweptPath')
        self.toolbar.setObjectName('QgisSweptPath')

        self.pluginIsActive = False
        self.dockwidget = None

        # Qgis property strings
        self._property_strings: dict[str, str] = {
            "vehicle_layer_id": "qgissweptpath/vehicle_layer",
            "path_layer_id": "qgissweptpath/path_layer"
        }

        # SweptPath fields
        self.simulation_running: bool = False  # Simulation is running
        self._simulation_id: str = ""  # Simulation ID for layer features identification
        self.vehicle: Vehicle = None  # The vehicle to simulate
        self._print_path: bool = True  # Property, if the path should be printed. If no path layer is present this will be set to false
        self._path_points: list[PathPoints] = []  # Stores all the path points during simulation

        # Controls the printing iteration
        self._print_iteration: int = 0  # Increments with each simulation step and will be set to 0 when a print was run
        self._print_interval: int = 10  # Interval. Each nth step the vehicle point will be stored/printed

        # Visualisation
        self._vehicle_layer: QgsVectorLayer = None  # Layer to draw the vehicle during simulation
        self._path_layer: QgsVectorLayer = None  # Layer to draw the swept path
        self._vehicle_features: dict[Vehicle, QgsFeature] = {}  # Dict with vehicle and the corresponding feature

    def run(self):
        """Run method that loads and starts the plugin"""

        if not self.pluginIsActive:
            self.pluginIsActive = True

            # dockwidget may not exist if:
            #    first run of plugin
            #    removed on close (see self.onClosePlugin method)
            if self.dockwidget is None:
                # Create the dockwidget
                self.dockwidget = QgisSweptPathDockWidget()

                # Setup Controls
                self.setupControls()

            # connect to provide cleanup on closing of dockwidget
            self.dockwidget.closingPlugin.connect(self.onClosePlugin)

            # Signals
            self.dockwidget.btnStartStopSimulation.clicked.connect(self.startStopSimulation)
            self.dockwidget.btnAddVehicleLayer.clicked.connect(self._create_vehicle_layer)
            self.dockwidget.btnAddPathLayer.clicked.connect(self._create_path_layer)
            self.dockwidget.btnCreateVehicle.clicked.connect(self._setup_vehicle)
            self.dockwidget.btnPlaceVehicle.clicked.connect(self._place_vehicle)

            self.setupLayers()

            # show the dockwidget
            self.iface.addDockWidget(Qt.RightDockWidgetArea, self.dockwidget)
            self.dockwidget.show()

    def setupControls(self):
        """Adds all actions for the controls"""
        # Actions
        self.add_action("Steer left",
                        self.steer_left,
                        add_to_menu=True,
                        parent=self.iface.mainWindow(),
                        shortcut="Ctrl+Shift+J")
        self.add_action("Steer right",
                        self.steer_right,
                        add_to_menu=True,
                        parent=self.iface.mainWindow(),
                        shortcut="Ctrl+Shift+L")
        self.add_action("Speed up",
                        self.speed_up,
                        add_to_menu=True,
                        parent=self.iface.mainWindow(),
                        shortcut="Ctrl+Shift+I")
        self.add_action("Speed down",
                        self.speed_down,
                        add_to_menu=True,
                        parent=self.iface.mainWindow(),
                        shortcut="Ctrl+Shift+K")
        self.add_action("Start/Stop simulation",
                        self.startStopSimulation,
                        add_to_menu=True,
                        parent=self.iface.mainWindow(),
                        shortcut="Ctrl+Shift+U")

    def setupLayers(self):
        """
        Method is called on plugin start.

        Try to load the layers (vehicle and path) from the stored ids in the project settings
        If no ids are stored (swept path plugin is never used before in this project) or the layers are not available
        (layer deleted since last run) new vehicle and/or path layers are created and the ids saved in the project
        """
        # Get the layer ids from the Qgis settings
        settings = QgsSettings()
        vehicle_layer_id = settings.value(self._property_strings["vehicle_layer_id"], None)
        path_layer_id = settings.value(self._property_strings["path_layer_id"], None)

        # Vehicle layer
        if vehicle_layer_id is None:
            # Create new layer if there is no id stored in the project
            self._create_vehicle_layer()
        else:
            # Get the layer by the id
            vehicle_layer = QgsProject.instance().mapLayer(vehicle_layer_id)
            if vehicle_layer is None:
                # If the layer is not available create new layer
                self.iface.messageBar().pushMessage(
                    "Vehicle layer not available",
                    "The stored vehicle layer is not available. A new vehicle layer will be created and saved in this project",
                    level=Qgis.Info
                )
                self._create_vehicle_layer()
            else:
                # Save reference to the existing layer and show the id in the text field
                self._vehicle_layer = vehicle_layer
                self.dockwidget.txtVehicleLayer.setText(vehicle_layer_id)

        # Path layer (details see vehicle layer above)
        if path_layer_id is None:
            self.iface.messageBar().pushMessage(
                "Path layer not available",
                "No Path layer is available. Create a new path layer manually",
                level=Qgis.Info
            )
        else:
            path_layer = QgsProject.instance().mapLayer(path_layer_id)
            if path_layer is None:
                self.iface.messageBar().pushMessage(
                    "Path layer not available",
                    "The stored path layer is not available. Create a new path layer manually",
                    level=Qgis.Info
                )
            else:
                self._path_layer = path_layer
                self.dockwidget.txtPathLayer.setText(path_layer_id)


    def setup_path_points(self):
        self._path_points = []  # Clear the list
        for v in self.vehicle.vehicle_parts:
            v_type = "main" if v.is_main_vehicle else "child"
            self._path_points.append(PathPoints(v, v.vehicle_name, v_type, "virtual", "f"))

            if v.has_body:
                # Setup body points
                p_type = "body"
                self._path_points.append(PathPoints(v, v.vehicle_name, v_type, p_type, "fl"))
                self._path_points.append(PathPoints(v, v.vehicle_name, v_type, p_type, "fr"))
                self._path_points.append(PathPoints(v, v.vehicle_name, v_type, p_type, "bl"))
                self._path_points.append(PathPoints(v, v.vehicle_name, v_type, p_type, "br"))

            if v.has_front_axle:
                # Setup front axle points
                p_type = "wheel"
                self._path_points.append(PathPoints(v, v.vehicle_name, v_type, p_type, "fwl"))
                self._path_points.append(PathPoints(v, v.vehicle_name, v_type, p_type, "fwr"))

            if v.has_rear_axle:
                p_type = "wheel"
                # Setup rear axle points
                self._path_points.append(PathPoints(v, v.vehicle_name, v_type, p_type, "rwl"))
                self._path_points.append(PathPoints(v, v.vehicle_name, v_type, p_type, "rwr"))


    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""
        icon_path = ":/plugins/qgis_swept_path/icon.png"
        self.add_action(
            text="QgisSweptPath",
            callback=self.run,
            icon_path=icon_path,
            enabled_flag=True,
            add_to_menu=True,
            parent=self.iface.mainWindow())


    def onClosePlugin(self):
        """Cleanup necessary items here when plugin dockwidget is closed"""
        # disconnects
        self.stopSimulation()
        self.dockwidget.closingPlugin.disconnect(self.onClosePlugin)
        self.pluginIsActive = False


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu('QgisSweptPath', action)
            self.iface.removeToolBarIcon(action)
            self.iface.unregisterMainWindowAction(action)
            QgsGui.shortcutsManager().unregisterAction(action)
        # remove the toolbar
        del self.toolbar


    def add_action(
        self,
        text,
        callback,
        icon_path=None,
        enabled_flag=True,
        add_to_menu=False,
        add_to_toolbar=False,
        status_tip=None,
        whats_this=None,
        parent=None, 
        shortcut=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :param shortcut: Optional text for keyboard shortcut. Default None
        :type shortcut: str

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)
        
        if shortcut is not None:
            self.iface.registerMainWindowAction(action, shortcut)
            QgsGui.shortcutsManager().registerAction(action)
            
        self.actions.append(action)

        return action

    def update_speed(self):
        self.dockwidget.txtSpeed.setText("{:.2f} km/h".format(self.vehicle.speed * 3.6))

    def update_steering(self):
        self.dockwidget.txtSteeringAngle.setText("{:.2f} °".format(self.vehicle.steering_angle / 3.14159 * 180))

    def speed_up(self):
        if self.simulation_running:
            self.vehicle.speed_up()
            self.update_speed()

    def speed_down(self):
        if self.simulation_running:
            self.vehicle.speed_down()
            self.update_speed()

    def steer_left(self):
        if self.simulation_running:
            self.vehicle.steer_left()
            self.update_steering()
    
    def steer_right(self):
        if self.simulation_running:
            self.vehicle.steer_right()
            self.update_steering()

    def startStopSimulation(self):
        # Starts or stops the simulation based on current status
        if self.simulation_running:
            self.stopSimulation()
        else:
            self.startSimulation()
    
    def stopSimulation(self):
        self.simulation_running = False
        self.dockwidget.btnStartStopSimulation.setText("START")
        if self._print_path:
            self._write_path_to_layer()

    def startSimulation(self):
        if (self.dockwidget.txtSimulationId.text() is None
                or len(str(self.dockwidget.txtSimulationId.text()).strip()) < 1)\
                or self._simulation_id == str(self.dockwidget.txtSimulationId.text()).strip():
            self._simulation_id = str(uuid4())
            self.dockwidget.txtSimulationId.setText(self._simulation_id)
        else:
            self._simulation_id = self.dockwidget.txtSimulationId.text()

        # The vehicle must first be created manually and be placed
        if self.vehicle is not None and self.vehicle.is_placed:
            # Checks if print path is set to true
            if self._print_path is True:
                self.setup_path_points()

            # Update the text fields with the steering and speed
            self.update_steering()
            self.update_speed()

            # Start simulation in separate thread
            self.simulation_running = True
            t = Thread(target=self.simulate, args=())
            t.start()
            self.dockwidget.btnStartStopSimulation.setText("STOP")
        else:
            self.iface.messageBar().pushMessage(
                "Can't start simulation",
                "The vehicle must first be created and placed",
                level=Qgis.Critical
            )

    def simulate(self):
        points = []
        while self.simulation_running:
            if self.vehicle.speed > 0.05:
                self.vehicle.step()
                point = QgsPoint(self.vehicle.f.x, self.vehicle.f.y)
                points.append(point)
                if not self.canvas.isDrawing():
                    self._draw_vehicle()
                time.sleep(self.vehicle.simulation_step / self.vehicle.speed)

                if self._print_path:
                    self._store_path_points()
            else:
                pass

    def _setup_vehicle(self):
        # TODO: Add a vehicle factory
        trailer = MercedesCitaroGTrailer()
        self.vehicle = MercedesCitaroG()
        self.vehicle.trailer = trailer

    def _place_vehicle(self):
        # Place the vehicle with the VehiclePlacer class
        if self.vehicle is not None:
            self._vehicle_placer = VehiclePlacer(self.iface, self.vehicle)  # Tool for placing vehicle
            self._vehicle_placer.placed.connect(self._vehicle_placed)
            self.canvas.setMapTool(self._vehicle_placer)
        else:
            self.iface.messageBar().pushMessage(
                "Can't place vehicle",
                "The vehicle must first be created",
                level=Qgis.Critical
            )

    def _vehicle_placed(self):
        # Unset the VehiclePlacer and draw the vehicle
        # Method is called, when the VehiclePlacer is finish
        self.canvas.unsetMapTool(self._vehicle_placer)
        self.iface.actionPan().trigger()
        self._create_vehicle_drawing()
        self._draw_vehicle()
        
    def _draw_vehicle(self):
        self._vehicle_layer.dataProvider().truncate()
        for v, f in self._vehicle_features.items():
            f["rotation"] = CoordUtils.rad_to_degrees(v.a) * -1
            f["wheel_angle"] = CoordUtils.rad_to_degrees(v.steering_angle)
            f.setGeometry(QgsGeometry.fromPointXY(QgsPointXY(v.f.x, v.f.y)))
            self._vehicle_layer.dataProvider().addFeatures([f])

        self._vehicle_layer.triggerRepaint()

    def _create_vehicle_drawing(self):
        self._vehicle_layer.dataProvider().truncate()
        for v in self.vehicle.vehicle_parts:
            feature = QgsFeature(self._vehicle_layer.fields())
            feature["symbol"] = v.get_symbol_path()
            feature["rotation"] = CoordUtils.rad_to_degrees(v.a) * -1
            feature["size_x"] = v.symbol_size_x
            feature["size_y"] = v.symbol_size_y
            feature["offset_x"] = v.symbol_offset_x
            feature["offset_y"] = v.symbol_offset_y
            feature["wheel_angle"] = CoordUtils.rad_to_degrees(v.steering_angle)
            feature.setGeometry(QgsGeometry.fromPointXY(QgsPointXY(v.f.x, v.f.y)))
            self._vehicle_features[v] = feature

            self._vehicle_layer.dataProvider().addFeatures([feature])

        self._vehicle_layer.triggerRepaint()

    def _store_path_points(self):
        # Store the vehicle points in a list
        if self._print_iteration == self._print_interval:
            for p in self._path_points:
                p.add_point(getattr(p.vehicle, p.vehicle_part))
            self._print_iteration = 0
        else:
            self._print_iteration += 1


    def _write_path_to_layer(self):
        # Write the stored points as lines to the layer
        for p in self._path_points:
            feature = QgsFeature(self._path_layer.fields())
            feature["simulation_id"] = self._simulation_id
            feature["vehicle_name"] = p.vehicle_name
            feature["vehicle_type"] = p.vehicle_type
            feature["vehicle_part_type"] = p.vehicle_part_type
            feature["vehicle_part"] = p.vehicle_part
            feature.setGeometry(QgsGeometry.fromPolylineXY(p.get_list_as_qgs_points()))
            self._path_layer.dataProvider().addFeatures([feature])

        self._path_layer.triggerRepaint()


    def _create_vehicle_layer(self):
        """
        Create a new in memory vector layer to show the vehicle during simulation
        """
        if self._vehicle_layer is not None:
            # Print the message, when the vehicle layer already exists
            self.iface.messageBar().pushMessage(
                "New vehicle Layer",
                "A new vehicle layer is created and saved in this project",
                level=Qgis.Info
            )

        # Create new vector layer and set Crs to project crs
        self._vehicle_layer = self.iface.addVectorLayer("Point", "vehicle", "memory")
        crs = QgsProject.instance().crs()
        self._vehicle_layer.setCrs(crs)

        # Add the attributes
        self._vehicle_layer.dataProvider().addAttributes([QgsField("symbol", QVariant.String)])
        self._vehicle_layer.dataProvider().addAttributes([QgsField("rotation", QVariant.Double)])
        self._vehicle_layer.dataProvider().addAttributes([QgsField("size_x", QVariant.Double)])
        self._vehicle_layer.dataProvider().addAttributes([QgsField("size_y", QVariant.Double)])
        self._vehicle_layer.dataProvider().addAttributes([QgsField("offset_x", QVariant.Double)])
        self._vehicle_layer.dataProvider().addAttributes([QgsField("offset_y", QVariant.Double)])
        self._vehicle_layer.dataProvider().addAttributes([QgsField("wheel_angle", QVariant.Double)])
        self._vehicle_layer.updateFields()

        # Add layer as new map layer
        QgsProject.instance().addMapLayer(self._vehicle_layer)

        # Save the id of the map layer in the project and show the id in the text field
        settings = QgsSettings()
        vehicle_layer_id = self._vehicle_layer.id()
        settings.setValue(self._property_strings["vehicle_layer_id"], vehicle_layer_id)
        self.dockwidget.txtVehicleLayer.setText(vehicle_layer_id)

    def _create_path_layer(self):
        """
        Create a new vector layer to print the paths
        """
        if self._path_layer is not None:
            # Print the message, when the path layer already exists
            self.iface.messageBar().pushMessage(
                "New path layer",
                "A new path layer is created and saved in this project",
                level=Qgis.Info
            )

        self._path_layer = self.iface.addVectorLayer("LineString", "path", "memory")
        crs = QgsProject.instance().crs()
        self._path_layer.setCrs(crs)

        # Add the attributes
        self._path_layer.dataProvider().addAttributes([QgsField("simulation_id", QVariant.String)])
        self._path_layer.dataProvider().addAttributes([QgsField("vehicle_name", QVariant.String)])
        self._path_layer.dataProvider().addAttributes([QgsField("vehicle_type", QVariant.String)])
        self._path_layer.dataProvider().addAttributes([QgsField("vehicle_part_type", QVariant.String)])
        self._path_layer.dataProvider().addAttributes([QgsField("vehicle_part", QVariant.String)])
        self._path_layer.updateFields()

        # Add layer as new map layer
        QgsProject.instance().addMapLayer(self._path_layer)

        # Save the id of the map layer in the project and show the id in the text field
        settings = QgsSettings()
        path_layer_id = self._path_layer.id()
        settings.setValue(self._property_strings["path_layer_id"], path_layer_id)
        self.dockwidget.txtPathLayer.setText(path_layer_id)

        # Show dialog to save the path layer to file/database
        save_dialog = QgsVectorLayerSaveAsDialog(self._path_layer, QgsVectorLayerSaveAsDialog.Option.Symbology)
        if save_dialog.exec():
            # If dialog returns true
            save_options = QgsVectorFileWriter.SaveVectorOptions()  # Create save options
            save_options.layerName = save_dialog.layerName()  # Set layer name
            transform_context = QgsProject.instance().transformContext()  # Transform context
            # Save layer to file
            writer_error = QgsVectorFileWriter.writeAsVectorFormatV3(self._path_layer,
                                                              save_dialog.fileName(),
                                                              transform_context,
                                                              save_options)

            if writer_error[0] == QgsVectorFileWriter.NoError:
                # When saved successfully, set the data source to the saved layer
                self._path_layer.setDataSource(
                    "{}|layername={}".format(save_dialog.fileName(), save_dialog.layerName()),
                    self._path_layer.name(),
                    'ogr')
            else:
                # On error show message and keep local layer
                self.iface.messageBar().pushWarning(
                    "Local path layer",
                    "Path layer could not be saved to file. Only a memory layer is created. All geometries will be lost"
                    "when the project is closed. The created layer must be saved manually",
                )
        else:
            # On error or when canceled show message and keep local layer
            self.iface.messageBar().pushWarning(
                "Local path layer",
                "Path layer could not be saved to file. Only a memory layer is created. All geometries will be lost"
                "when the project is closed. The created layer must be saved manually",
            )
